services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-diagram-repro
    ports: ["3000:3000"]
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=jdbranham-diagram-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-diagram/dist:/var/lib/grafana/plugins/jdbranham-diagram-panel
      - ./grafana/provisioning:/etc/grafana/provisioning
